{% set version = "1.3.0" %}
{% set name = "gf2x" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://gitlab.inria.fr/gf2x/gf2x/-/archive/gf2x-{{ version }}/gf2x-gf2x-{{ version }}.tar.bz2
  sha256: 741694fac29d56edf58b42dc9827c85303090522ccdd1e89c311c6b22c290efa
  patches:
    - fix-exit.diff
    - fix-asprintf.diff

build:
  number: 3
  run_exports:
    - {{ pin_subpackage('gf2x', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - libtool                   # [unix]
    - automake                  # [unix]
    - autoconf                  # [unix]
    - make                      # [unix]
    - m4                        # [unix]
    - autotools_clang_conda     # [win]
  host:
  run:

test:
  commands:
    - test -f $PREFIX/include/gf2x.h               # [unix]
    - test ! -f $PREFIX/lib/lib{{ name }}.a        # [unix]
    - test -f $PREFIX/lib/lib{{ name }}.so         # [linux]
    - test -f $PREFIX/lib/lib{{ name }}.dylib      # [osx]
    - if not exist %LIBRARY_BIN%\\gf2x-3.dll exit 1         # [win]
    - if not exist %LIBRARY_LIB%\\gf2x.lib exit 1           # [win]
    - if exist %LIBRARY_LIB%\\gf2x_static.lib exit 1        # [win]
    - if not exist %LIBRARY_INC%\\gf2x.h exit 1             # [win]

about:
  home: http://gf2x.gforge.inria.fr
  dev_url: http://gforge.inria.fr/projects/gf2x/
  license: LGPL-2.1-or-later
  license_file:
    - COPYING
    - COPYING.LIB
  summary: gf2x is a library for multiplying polynomials over the binary field.
  description: |
    gf2x is a C/C++ software package containing routines for fast arithmetic
    in GF(2)[x] (multiplication, squaring, GCD) and searching for
    irreducible/primitive trinomials.

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
